### ISSUE TITLE
Multi-Zone Support

### ISSUE THREAD

**Issue by aweingarten** [adweingarten/cloudflare#12]
### Business Requirements
- [ ] As a user of cloudFlare, with a multi-zone account I want the module to purge the correct zone.
### Background

Since free tier only has a single zone some shortcuts were taken which assume that there is only one zone. 
### Technical Requirements
- [ ] Talk through use-cases for multi-zone configurations.
- [ ] Setup a site with multiple CloudFlare zones.
- [ ] Test changing settings and confirm that the correct zone is updated.
- [ ] Test cache clearing and confirm that the correct zone is updated. 
- [ ] Ensure that any multizone selects or UX are hidden in a single zone account.
- [ ] Add description text to explain what a zone is since its super confusing.

**Comment by wimleers** [comment]
Why is this exposed in the UI by default? 99% of users don't need to ever see or use this.

**Comment by aweingarten** [comment]
I could see this being an issue on a PS build.  I'm reluctant to assume that users will be working with a single zone account.  That being said in a single zone system we should make sure that we set sane defaults so we don't add complexity.  In those situation we should hide the zone selection.

**Comment by wimleers** [comment]
But even the single zone exposed right now can be _wrong_! When only enabling CloudFlare for a subdomain, the zone displayed is for the root domain. This is super confusing.

**Comment by aweingarten** [comment]
Moved to D.O
