### ISSUE TITLE
Add UX for Manual purge by tag on CloudFlare

### ISSUE THREAD

**Issue by aweingarten** [adweingarten/cloudflare#7]
### Requirements
- [ ] As a user I want the ability to manually purge tags on cloudflare. 
- [ ] Update existing purge by path to allow purge by tag.  
- [ ] Expose a dropdown with a list of tags that users can choose from.  
- [ ] Add a radio to allow users to invoke internal drupal cache-clear framework OR cloudflare-purge directly.  
- [ ] Add text explaining that the preferred method is to use purge but that this can be used for troubleshooting
- [ ] Add automated testing
### Background

You should be able to follow the pattern here: 
https://github.com/d8-contrib-modules/cloudflare/blob/master/src/Form/CloudFlareCacheClearForm.php

**Comment by wimleers** [comment]
-1

We don't want manual tag purging.

Besides:

>  Expose a dropdown with a list of tags that users can choose from.

this would be an absolutely terrible experience, since the number of tags scales with the amount of content. Furthermore, you cannot create a comprehensive list of cache tags; only calling code knows those.

**Comment by aweingarten** [comment]
Sounds reasonable to me.  Closing.
